{{- $monitoring := include "python-app.monitoring" . | fromYaml }}
{{- if and $monitoring.enabled $monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
    {{- with $monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "python-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ $monitoring.serviceMonitor.scrapeTimeout }}
{{- end }} 